#!/bin/bash

set -eu
set -o pipefail

baseurl='https://dl.google.com/linux/chrome/deb'

url=$(
  wget -q -O - "${baseurl}/dists/stable/main/binary-amd64/Packages" \
    | awk -v "baseurl=${baseurl}" '
       BEGIN { found = 0 }
       $1 == "Package:" && $2 == "google-chrome-stable" {
         in_stable_section = 1
       }
       in_stable_section && $1 == "Filename:" {
         if (!found) {
           print baseurl "/" $2
           found = 1
         }
      }')

if [ -z "$url" ]; then
  echo 'url not found' >&2
  exit 1
fi

printf "%s\n" "$url" > upstream_pack_url

checksum=$(wget -qO - "$url" | sha384sum | awk '{ print $1 }')
if [ -z "$checksum" ]; then
  echo 'checksum could not be calculated' >&2
  exit 1
fi

printf "%s\n" "$checksum" > upstream_pack_sha384sum
